### ISSUE TITLE
[Feature Request] Include tags as labels on metrics

### ISSUE THREAD

**Issue by jw-s** [thought-machine/aws-service-quotas-exporter#21]
We tag our vpcs with various metadata regarding how we use them and would love to have this information present in the returned metrics. This would help us determine the criticality of IP shortage in Subnet X for example. What do you think about this? This could be guarded with a cmdline flag which is disabled by default? I'm more than happy to include this if you agree.

**Comment by idgenchev** [comment]
That does indeed sound like a useful feature for this exporter as long as it's generic enough. What is that going to look like for IAM or Route 53 quota metrics for example?

**Comment by jw-s** [comment]
@idgenchev Each quota in each service in the service quotas can have tags so i was just planning on utilising this. If you can add tags on a particular service then it's a no-op. WDYT? Maybe I don't get you?

**Comment by idgenchev** [comment]
@jw-s I'm afraid that's not quite the case (unless I'm misunderstanding you 🙈 ).

We export two types of metrics:
 1. Metrics that are tied to a resource, such as the `aws_rules_per_security_group_limit_total` and `aws_available_ips_per_subnet_limit_total ` for example. These can come from the AWS service quotas API (and we have custom logic just to fill in usage) or can be custom and the `Usage` method just fills in both (usage and limit) as is the case with the IPs per subnet.
 2. Metrics that are not tied to a resource, such as the `aws_spot_instance_requests_limit_total` and `aws_ondemand_instance_requests_limit_total ` for example.

In the case of IPs per subnet metric, the resource is the subnet itself. If we're to add the resource tags to the `aws_available_ips_per_subnet_limit_total` metric, it makes sense to me to add the tags of the subnet and not the VPC that the subnet is in. That way it'll be straightforward, I think - just extend the `QuotaUsage` with something like `tags map[string]string` and add the resource tags as labels for each metric (could be guarded with a flag).

Adding the tags of the VPC to the metric is possible for `aws_available_ips_per_subnet_limit_total` as that's in a VPC, but not for the Spot instance requests metric for example as those are per account and won't have tags at all as they're not tied to a particular resource. There are also service quotas for services like IAM, Route 53, etc which won't be tied to a VPC and their resources can also have tags attached to them (and we'd like to cover all AWS services with this exporter eventually). That's why I think that it makes sense to just add the resource (eg subnet, security group) tags as labels for each metric (if the metric is tied to a resource).

What do you think about that?

**Comment by jw-s** [comment]
> We tag our vpcs with various metadata....

Ahh sorry I think I confused you when I mentioned the above, the vpc was just an example. Indeed i would just include the tags for the resource in question/related to the metric. But for the `aws_spot_instance_requests_limit_total` this is populated by the service quotas api, each quota is like an AWS resource and can have tags too :). So we can just add those, since like you said, `Tags` will just another field in the struct.

**Comment by jw-s** [comment]
You also mentioned about putting the tags of the VPC on the subnet metric. Do we want to do this or would it be better to do the subnet tags itself since that's the resource? We can always include the vpc_id as a label to show the relationship?

**Comment by idgenchev** [comment]
> > We tag our vpcs with various metadata....
> 
> Ahh sorry I think I confused you when I mentioned the above, the vpc was just an example. Indeed i would just include the tags for the resource in question/related to the metric. But for the `aws_spot_instance_requests_limit_total` this is populated by the service quotas api, each quota is like an AWS resource and can have tags too :). So we can just add those, since like you said, `Tags` will just another field in the struct.

No worries at all, looks like we're on the same page then :) That sounds good to me in that case.

> You also mentioned about putting the tags of the VPC on the subnet metric. Do we want to do this or would it be better to do the subnet tags itself since that's the resource? We can always include the vpc_id as a label to show the relationship?

For this one, I think it's better to just do the subnet tags so we keep everything consistent.

**Comment by idgenchev** [comment]
The only thing I would add is that this feature should definitely be behind a flag and it should be disabled by default as the unique key-value pairs for those labels is unpredictable and so can potentially have very high cardinality, which can dramatically increase the amount of data stored.

**Comment by jw-s** [comment]
Cool i'll get to work then :)
